all:  P11.c P12.c P21.c P22.c Q1.C Q2.C
	gcc -Wall -std=c99 P11.c  -o P11
	gcc -Wall -std=c99 P12.c  -o P12
	gcc -Wall -std=c99 P21.c  -o P21
	gcc -Wall -std=c99 P22.c  -o P22
	gcc -Wall -std=c99 P23.c  -o P23
	gcc -Wall -std=c99 Q1.c  -o Q1
	gcc -Wall -std=c99 Q2.c  -o Q2

P11: P11.c
	gcc -Wall -std=c99 P11.c  -o P11
P12: P12.c
	gcc -Wall -std=c99 P12.c  -o P12
P21: P21.c
	gcc -Wall -std=c99 P21.c  -o P21
P22: P22.c
	gcc -Wall -std=c99 P22.c  -o P22
Q1: Q1.c
	gcc -Wall -std=c99 Q1.c  -o Q1
Q2: Q2.c
	gcc -Wall -std=c99 Q2.c  -o Q2

clean:
	rm P11 P12 P21 P22 P23 Q1 Q2